version: '3'
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8888:8888
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - forum-postgres 
    networks:
      - forum

  forum-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - forum

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - forum-postgres
    ports:
      - "5050:80"
    networks:
      - forum
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  forum:
    driver: bridge